# Generated by Django 6.1.1 on 2026-09-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prouduct_name', models.CharField(max_length=150, null=True)),
                ('description', models.TextField(null=True)),
                ('product_date', models.DateField(null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('product_type', models.CharField(choices=[('fruits', 'Fruits'), ('grocery', 'Grocery'), ('fashion', 'Fashion')], max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
